core : 7.x
api : 2
projects[drupal][version] = 7
projects[admin_menu][subdir] = contrib
projects[module_filter][subdir] = contrib
projects[menu_attributes][subdir] = contrib
projects[devel][subdir] = contrib
projects[features][subdir] = contrib
projects[ctools][subdir] = contrib
projects[strongarm][subdir] = contrib
projects[entity][subdir] = contrib
projects[libraries][subdir] = contrib
projects[panels][subdir] = contrib
projects[site_map][subdir] = contrib
projects[page_title][subdir] = contrib
projects[xmlsitemap][subdir] = contrib
projects[pathauto][subdir] = contrib
projects[token][subdir] = contrib
projects[views][subdir] = contrib
projects[ckeditor][subdir] = contrib
libraries[ckeditor][download][type] = get
libraries[ckeditor][download][url] = http://download.cksource.com/CKEditor/CKEditor/CKEditor%204.0.1/ckeditor_4.0.1_standard.tar.gz
libraries[ckeditor][destination] = libraries
